### ISSUE TITLE
Allow Date Variables In States

### ISSUE THREAD

**Issue by KabirSuri** [echo-lab/iThem#2]
As of now, it is very complicated to store **dates** as states in iThem. If a user wants to incorporate "date" variables, they must make an **entire algorithm** where a string is originally set to null, then alternates between a Date object and string. For example,  a date variable would be initialized as null, then would be loaded into iThem as an integer, then converted into a Date, which is then saved into iThem's states as a String. Useful calculations like **finding the difference in hours between two dates** would be difficult.

**Comment by panavrin** [comment]
yup. I think this is a good idea. In general, I don't know if we should make users have to specify the type of state variables. 

Maybe a user should be able to save any javascript object? that's a better solution? What do you think? If you agree, I would close this issue and create a new one (or revise this one to "allow users to save javascript objects in state variables")
